/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;


class LibraryTest {
    Library sut = new Library();
    @Test void rollNumbersCheck_IfNotInRange_1To6_ReturnFalse() {
        int [] rolls = sut.roll(4);
        for (int roll : rolls) {
            assertFalse(roll < 1 || roll > 6);
        }
    }

    @Test void rollDiceindexTest() {
        int index = sut.roll(4).length;
        Assertions.assertEquals(4,index);
    }
    @Test void rollsWithNegativeNumber_ReturnZero() {
        int acutal = sut.roll(-1).length;
        Assertions.assertEquals(0,acutal);
    }
    @Test void rollsWithZeroNumber_ReturnZero() {
        int acutal = sut.roll(0).length;
        Assertions.assertEquals(0,acutal);
    }
    @Test void noDuplicates_ReturnFalse() {
        Assertions.assertEquals(false , sut.findDuplicates(new int[]{66, 64, 58, 65, 71, 57, 60}));
    }
    @Test void oneDuplicate_ReturnTrue() {
        Assertions.assertEquals(true , sut.findDuplicates(new int[]{57, 65, 65, 70, 72, 65, 51}));
    }
    @Test void emptyArray_findDuplicates_ReturnFalse () {
        Assertions.assertEquals(false , sut.findDuplicates(new int[]{}));
    }
    @Test void allArrayDuplicate_ReturnTrue () {
        Assertions.assertEquals(true , sut.findDuplicates(new int[]{15,15,15,15,15,15}));
    }

    @Test void caluclateAverage_WithPostivieValues_ReturnAverage() {
        Assertions.assertEquals(2.75,sut.caluculateAverage(new int[] {3,2,5,1}));
    }
    @Test void calculateAverage_WithNegativeValues_ReturnNegativeAverage() {
        Assertions.assertEquals(-2.75,sut.caluculateAverage(new int[] {-3,-2,-5,-1}));
    }
    @Test void calculateAverage_WithZeroValues_ReturnAverage(){
        Assertions.assertEquals(1,sut.caluculateAverage(new int[] {3,0,0,1}));
    }
    @Test void calculateAverage_WithOnlyZeros_ReturnZero() {
        Assertions.assertEquals(0,sut.caluculateAverage(new int[] {0,0,0,0}));
    }
    @Test void calculateAverage_WithNoElemntsInArray_ReturnNaN() {
        Assertions.assertEquals(Double.NaN,sut.caluculateAverage(new int[] {}));
    }
    @Test void calculateAverage_WithSingleElement_ReturnAverage() {
        Assertions.assertEquals(6,sut.caluculateAverage(new int[] {6}));
    }
    @Test void arrayOfArrays() {
        int [] actual = sut.arrayOfArrays(new int[][] {
                {66, 64, 58, 65, 71, 57, 60}, //63
                {57, 65, 65, 70, 72, 65, 51}, //63.5
                {55, 54, 60, 53, 59, 57, 61}, //57
                {65, 56, 55, 52, 55, 62, 57}  //57,4
        });
        Assertions.assertArrayEquals(new int[] {55, 54, 60, 53, 59, 57, 61}, actual);
    }
}
