/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Path filePath = Path.of("./src/main/resources/gates.js");
//        System.out.println(System.getProperty("user.dir"));
        List<String> errors = findMissingSemicolons(filePath);

        if (!errors.isEmpty()) {
            System.out.println("Errors found:");
            for (String error : errors) {
                System.out.println(error);
            }
        } else {
            System.out.println("No errors found.");
        }
    }


    public static List<String> findMissingSemicolons(Path filePath) {
        List<String> errorMessages = new ArrayList<>();
        int lineCounter = 0;

        try {
            List<String> lines = Files.readAllLines(filePath);

            for (String line : lines) {
                lineCounter++;
                if (line.trim().isEmpty() || line.trim().endsWith("{") || line.trim().endsWith("}") || line.contains("if") || line.contains("else")) {
                    continue;
                }

                if (!line.trim().endsWith(";")) {
                    errorMessages.add("Line " + lineCounter + ": Missing semicolon.");
                }
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        return errorMessages;
    }
}
